apiVersion: v1
kind: Pod
metadata:
  name: munnaapp
  labels:
    role: myrole
spec:
  containers:
    - name: mywebcon
      image: mrunalthak/mrunalapp
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
